- hosts: cd
  tasks:

    - name: Copy compose file
      copy:
        src: ../compose.yml
        dest: /home/debian/simple-project/compose.yml

    - name: Pull latest image
      command: podman-compose pull
      args:
        chdir: /home/debian/simple-project

    - name: Remove old containers
      command: podman-compose down
      args:
        chdir: /home/debian/simple-project
      ignore_errors: yes

    - name: Start containers
      command: podman-compose up -d --pull always --force-recreate
      args:
        chdir: /home/debian/simple-project