- hosts: cd

  tasks:

    - name: Copy compose file
      copy:
        src: ../compose.yml
        dest: /home/debian/simple-project/compose.yml

    - name: Pull latest image
      command: podman-compose pull
      args:
        chdir: /home/debian/simple-project

    - name: Recreate containers
      command: podman-compose up -d
      args:
        chdir: /home/debian/simple-project